# Generated by Django 5.1.5 on 2025-01-23 13:26

import datetime
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AddField(
            model_name='media',
            name='fileSize',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='mimeType',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='uploadedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 23, 13, 26, 57, 749324, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaFile',
            field=models.ImageField(help_text='Supported formats: JPG, JPEG, PNG, GIF', upload_to=posts.models.upload_to_path, validators=[posts.models.validate_file_extension]),
        ),
    ]
