# Generated by Django 5.1.5 on 2025-01-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_media_options_media_filesize_media_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='mimeType',
        ),
    ]
